name: Test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push,pull_request,workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: --name rabbitmq

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up RabbitMQ
      run: |
        until sudo lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
        ./bin/ci/before_build_docker.sh
    - name: Run tests
      run: bundle exec rspec spec
  test_all:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test (matrix)
    needs: test
    steps:
      - name: Check test matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
